version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    container_name: keycloak
    environment:
      # Hostname Configuration
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL}
      KC_HOSTNAME_ADMIN_URL: ${KC_HOSTNAME_ADMIN_URL}
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_PROXY: edge
      KC_LOG_LEVEL: debug
      # Database Configuration
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Admin Credentials
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Theme Configuration
      KC_SPI_THEME_DEFAULT: ${KEYCLOAK_THEME}
    restart: always
    ports:
      - ${PORT_KEYCLOAK}:8080
    volumes:
      - ./extensions:/opt/keycloak/providers/
      - ./themes/${KEYCLOAK_THEME}:/opt/keycloak/themes/${KEYCLOAK_THEME}
    networks:
      - nginx-proxy

  nginx:
    image: nginx:latest
    container_name: keycloak-nginx
    environment:
      # Reverse proxy Configuration
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${NGINX_ACCESS_PORT}
      HTTPS_METHOD: redirect
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - ${NGINX_ACCESS_PORT}:${NGINX_ACCESS_PORT}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
