version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    container_name: keycloak
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_DB: ${KC_DB}
      KC_DB_URL: jdbc:postgresql://${KC_DB_HOST}:${KC_DB_PORT}/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${PORT_KEYCLOAK}
      HTTPS_METHOD: redirect
      PROXY_ADDRESS_FORWARDING: "true"
    restart: always
    ports:
      - ${PORT_KEYCLOAK}:8080
    networks:
      - nginx-proxy

  nginx-configurator:
    build:
      context: ./nginx-configurator
    volumes:
      - /etc/nginx/conf.d
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
