services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    container_name: keycloak
    environment:
      # Hostname Configuration
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: debug
      KC_PROXY: edge
      # Database Configuration
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Admin Credentials
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    restart: always
    ports:
      - ${PORT_KEYCLOAK}:8080
    # volumes:
      # - ./themes/${KEYCLOAK_THEME}:/opt/keycloak/themes/${KEYCLOAK_THEME}
    networks:
      - cassava-network

networks:
  cassava-network:
    driver: bridge
